extension MDRProtocolFamily {
    /// Readable name for an announced function id. Ids the tables do not cover are still valid;
    /// they are simply ones this project has no use for yet.
    public func functionName(for id: UInt8) -> String? {
        switch self {
        case .v1: Self.v1Functions[id]
        case .v2: Self.v2Functions[id]
        }
    }

    private static let v1Functions: [UInt8: String] = [
        0x11: "battery level",
        0x12: "upscaling indicator",
        0x13: "codec indicator",
        0x15: "left/right battery level",
        0x17: "left/right connection status",
        0x18: "case battery level",
        0x21: "power off",
        0x30: "firmware update",
        0x38: "paired device management",
        0x39: "voice guidance",
        0x41: "virtual phones technology",
        0x42: "sound position",
        0x51: "preset equalizer",
        0x52: "clear bass",
        0x53: "preset equalizer, fixed",
        0x61: "noise cancelling",
        0x62: "noise cancelling + ambient sound",
        0x63: "ambient sound",
        0x71: "adaptive sound control",
        0x81: "noise cancelling optimizer",
        0xA1: "playback controller",
        0xC1: "action log",
        0xD1: "general setting 1",
        0xD2: "general setting 2",
        0xD3: "general setting 3",
        0xE1: "connection mode",
        0xE2: "upscaling",
        0xF2: "power saving mode",
        0xF3: "playback control by wearing",
        0xF4: "auto power off",
        0xF5: "speak-to-chat",
        0xF6: "assignable controls",
    ]

    private static let v2Functions: [UInt8: String] = [
        0x11: "connection status",
        0x12: "codec indicator",
        0x13: "upscaling indicator",
        0x1B: "firmware version",
        0x20: "battery level",
        0x21: "left/right battery level",
        0x22: "case battery level",
        0x23: "power off",
        0x24: "auto power off",
        0x25: "auto power off with wearing detection",
        0x26: "power saving mode",
        0x28: "battery level, with threshold",
        0x29: "left/right battery level, with threshold",
        0x2A: "case battery level, with threshold",
        0x2D: "bluetooth standby",
        0x50: "preset equalizer",
        0x51: "clear bass",
        0x52: "preset equalizer, fixed",
        0x53: "preset equalizer with ULT mode",
        0x55: "custom equalizer",
        0x61: "noise cancelling on/off",
        0x62: "noise cancelling + ambient on/off",
        0x63: "noise cancelling dual/single + ambient on/off",
        0x64: "noise cancelling + ambient level",
        0x65: "noise cancelling dual/single + ambient level",
        0x66: "ambient sound on/off",
        0x67: "ambient sound level",
        0x68: "noise cancelling dual/auto + ambient level",
        0x6A: "noise cancelling dual/single + ambient level, mode select",
        0x6B: "noise cancelling dual + ambient level, mode select",
        0x6D: "noise cancelling dual + ambient level, noise adaptive",
        0x70: "adaptive sound control",
        0x71: "adaptive control with notification",
        0x81: "noise cancelling optimizer",
        0xA1: "playback controller",
        0xD1: "general setting 1",
        0xD2: "general setting 2",
        0xD3: "general setting 3",
        0xD4: "general setting 4",
        0xE1: "connection mode",
        0xE2: "upscaling",
        0xE6: "listening option",
        0xF1: "playback control by wearing",
        0xF2: "speak-to-chat",
        0xF3: "assignable controls",
        0xF6: "wearing detection",
        0xFA: "auto volume",
        0xFC: "speak-to-chat, type 2",
        0xFD: "quick access",
        0xFF: "head gestures",
    ]
}
